import { StyleSheet } from 'react-native';

export const descriptionStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 40,
  },
  content: {
    padding: 20,
  },
  backButton: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 10,
  },
  backButtonAlt: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: '#F7FAFC',
    borderRadius: 8,
    alignSelf: 'center',
    marginTop: 20,
  },
  backButtonText: {
    fontSize: 16,
    color: '#4A5568',
    fontWeight: '600',
  },
  imageContainer: {
    height: 250,
    width: '100%',
  },
  campaignImage: {
    width: '100%',
    height: '100%',
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#2D3748',
    marginBottom: 20,
    textAlign: 'center',
    lineHeight: 32,
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: '#F7FAFC',
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  statItem: {
    alignItems: 'center',
  },
  statValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#4A5568',
    marginBottom: 5,
  },
  statLabel: {
    fontSize: 12,
    color: '#718096',
  },
  progressSection: {
    marginBottom: 20,
  },
  progressBarContainer: {
    marginBottom: 10,
  },
  progressBar: {
    height: 10,
    backgroundColor: '#E2E8F0',
    borderRadius: 5,
    marginBottom: 8,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#4A5568',
    borderRadius: 5,
  },
  progressText: {
    fontSize: 14,
    color: '#718096',
    textAlign: 'center',
  },
  description: {
    fontSize: 16,
    color: '#4A5568',
    lineHeight: 24,
    marginBottom: 30,
  },
  donationSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2D3748',
    marginBottom: 15,
  },
  amountSection: {
    marginBottom: 25,
  },
  amountLabel: {
    fontSize: 16,
    color: '#4A5568',
    marginBottom: 10,
    fontWeight: '600',
  },
  amountInput: {
    backgroundColor: '#F7FAFC',
    borderRadius: 10,
    padding: 15,
    fontSize: 18,
    color: '#2D3748',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 15,
  },
  presetAmounts: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  presetButton: {
    backgroundColor: '#4A5568',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
    minWidth: 70,
    alignItems: 'center',
  },
  presetButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 14,
  },
  paymentSection: {
    marginBottom: 25,
  },
  paymentOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F7FAFC',
    borderRadius: 10,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  paymentOptionSelected: {
    borderColor: '#4A5568',
    backgroundColor: '#EDF2F7',
  },
  radioContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  radio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#4A5568',
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioSelected: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#4A5568',
  },
  paymentOptionText: {
    fontSize: 16,
    color: '#2D3748',
    fontWeight: '600',
  },
  paymentIcon: {
    width: 24,
    height: 24,
    tintColor: '#4A5568',
  },
  paymentForm: {
    marginTop: 15,
    gap: 12,
  },
  input: {
    backgroundColor: '#F7FAFC',
    borderRadius: 10,
    padding: 15,
    fontSize: 16,
    color: '#2D3748',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  mobileMoneyNote: {
    fontSize: 12,
    color: '#A0AEC0',
    fontStyle: 'italic',
    textAlign: 'center',
    marginTop: 5,
    lineHeight: 16,
  },
  donateButton: {
    backgroundColor: '#4A5568',
    borderRadius: 25,
    paddingVertical: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  donateButtonDisabled: {
    backgroundColor: '#718096',
    opacity: 0.8,
  },
  donateButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  errorText: {
    fontSize: 18,
    color: '#2D3748',
    textAlign: 'center',
    marginBottom: 20,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  loadingText: {
    fontSize: 16,
    color: '#4A5568',
    marginTop: 10,
  },
  organizationContainer: {
    backgroundColor: '#F7FAFC',
    borderRadius: 8,
    padding: 12,
    marginBottom: 15,
    alignSelf: 'center',
  },
  organizationText: {
    fontSize: 14,
    color: '#4A5568',
    fontStyle: 'italic',
  },
  daysRemainingContainer: {
    backgroundColor: '#4A5568',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    alignSelf: 'center',
    marginBottom: 15,
  },
  daysRemainingText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 14,
  },
  statusBadge: {
    alignSelf: 'center',
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 12,
    marginTop: 10,
    marginBottom: 20,
  },
  statusActive: {
    backgroundColor: '#48BB78',
  },
  statusCompleted: {
    backgroundColor: '#38B2AC',
  },
  statusDraft: {
    backgroundColor: '#A0AEC0',
  },
  statusText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 12,
  },
  loginReminder: {
    backgroundColor: '#FEF3C7',
    borderLeftWidth: 4,
    borderLeftColor: '#D97706',
    padding: 12,
    borderRadius: 8,
    marginBottom: 15,
  },
  loginReminderText: {
    color: '#92400E',
    fontSize: 14,
    lineHeight: 20,
  },
});

export default descriptionStyles;